# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-30 02:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'\xe5\xba\x97\xe9\x8b\xaa\xe5\x90\x8d\xe7\xa8\xb1', max_length=20)),
                ('telephone', models.CharField(help_text=b'\xe9\x9b\xbb\xe8\xa9\xb1', max_length=11)),
                ('address', models.CharField(help_text=b'\xe5\x9c\xb0\xe5\x9d\x80', max_length=100)),
                ('opendate', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe9\x96\x8b\xe6\xa5\xad\xe6\x97\xa5\xe6\x9c\x9f')),
                ('note', models.CharField(blank=True, help_text=b'\xe5\x82\x99\xe8\xa8\xbb', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '\u5e97\u8216\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_eula', models.BooleanField()),
                ('favorite_animal', models.CharField(default=b'Dragon', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '\u4eba\u54e1\u7ba1\u7406',
            },
        ),
    ]
