# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-13 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=20)),
                ('cSex', models.CharField(default=b'M', max_length=2)),
                ('cBirthday', models.DateField()),
                ('cEmail', models.EmailField(blank=True, default=b'', max_length=100)),
                ('cPhone', models.CharField(blank=True, default=b'', max_length=50)),
                ('cAddr', models.CharField(blank=True, default=b'', max_length=255)),
            ],
        ),
    ]
