# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-04 12:19
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'\xe5\x88\x86\xe7\xb1\xbb\xe5\x90\x8d\xe7\xa7\xb0', max_length=10)),
                ('hidden', models.BooleanField(default=False, help_text=b'\xe6\x98\xaf\xe5\x90\xa6\xe9\x9a\x90\xe8\x97\x8f')),
                ('pid', models.ForeignKey(blank=True, help_text=b'\xe7\x88\xb6\xe7\xba\xa7\xe5\x88\x86\xe7\xb1\xbb', null=True, on_delete=django.db.models.deletion.CASCADE, to='psi.Category')),
            ],
            options={
                'verbose_name_plural': '\u5206\u7c7b\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'\xe9\xa1\xbe\xe5\xae\xa2\xe5\xa7\x93\xe5\x90\x8d', max_length=10)),
                ('code', models.CharField(blank=True, help_text=b'\xe7\xbc\x96\xe5\x8f\xb7', max_length=20, null=True)),
                ('telephone', models.CharField(blank=True, help_text=b'\xe8\x81\x94\xe7\xb3\xbb\xe7\x94\xb5\xe8\xaf\x9d', max_length=11, null=True)),
                ('address', models.CharField(blank=True, help_text=b'\xe5\x9c\xb0\xe5\x9d\x80', max_length=100, null=True)),
                ('joindate', models.DateField(blank=True, default=datetime.datetime(2018, 10, 4, 20, 19, 1, 448000), help_text=b'\xe5\x8a\xa0\xe5\x85\xa5\xe6\x97\xa5\xe6\x9c\x9f', null=True)),
                ('hidden', models.BooleanField(default=False, help_text=b'\xe5\x88\xa0\xe9\x99\xa4\xe6\xa0\x87\xe8\xae\xb0')),
                ('note', models.CharField(blank=True, help_text=b'\xe5\xa4\x87\xe6\xb3\xa8', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '\u987e\u5ba2\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'\xe4\xbb\x93\xe5\xba\x93\xe5\x90\x8d', max_length=10)),
                ('address', models.CharField(help_text=b'\xe4\xbb\x93\xe5\xba\x93\xe5\x9c\xb0\xe5\x9d\x80', max_length=100)),
                ('hidden', models.BooleanField(default=False, help_text=b'\xe6\x98\xaf\xe5\x90\xa6\xe9\x9a\x90\xe8\x97\x8f')),
                ('note', models.CharField(blank=True, help_text=b'\xe5\xa4\x87\xe6\xb3\xa8', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '\u4ed3\u5e93\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='InDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, help_text=b'\xe5\x8e\x82\xe6\x96\xb9\xe8\xbf\x9b\xe4\xbb\xb7', max_digits=8)),
                ('quantity', models.IntegerField(help_text=b'\xe6\x95\xb0\xe9\x87\x8f', max_length=5)),
                ('depotdetail', models.CharField(blank=True, help_text=b'\xe5\x87\xba\xe5\x85\xa5\xe5\xba\x93\xe8\xaf\xa6\xe7\xbb\x86\xe4\xbd\x8d\xe7\xbd\xae', max_length=100, null=True)),
                ('depot', models.ForeignKey(help_text=b'\xe5\x87\xba\xe5\x85\xa5\xe5\xba\x93\xe5\xba\x93\xe6\x88\xbf', on_delete=django.db.models.deletion.CASCADE, to='psi.Depot')),
            ],
            options={
                'verbose_name_plural': '\u5165\u5e93\u8be6\u5355',
            },
        ),
        migrations.CreateModel(
            name='InStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text=b'\xe5\x85\xa5\xe5\xba\x93\xe5\x8d\x95\xe5\x8f\xb7', max_length=30, unique=True)),
                ('supplier', models.SmallIntegerField(choices=[(1, b'\xe7\xbd\x97\xe8\x8e\xb1'), (2, b'\xe4\xbc\x98\xe5\xae\xb6'), (3, b'\xe5\xae\x9d\xe7\xbc\xa6'), (4, b'\xe5\x85\xb6\xe4\xbb\x96')], help_text=b'\xe4\xbe\x9b\xe5\xba\x94\xe5\x95\x86', max_length=2)),
                ('date', models.DateField(default=datetime.datetime(2018, 10, 4, 20, 19, 1, 448000), help_text=b'\xe6\x97\xa5\xe6\x9c\x9f')),
                ('note', models.CharField(blank=True, help_text=b'\xe5\xa4\x87\xe6\xb3\xa8', max_length=100, null=True)),
                ('log', models.TextField(blank=True, help_text=b'\xe5\xa4\x87\xe6\xb3\xa8', max_length=1500, null=True)),
                ('hidden', models.BooleanField(default=False, help_text=b'\xe5\x88\xa0\xe9\x99\xa4\xe6\xa0\x87\xe8\xae\xb0')),
            ],
            options={
                'verbose_name_plural': '\u5165\u5e93\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='OutDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text=b'\xe6\x95\xb0\xe9\x87\x8f', max_length=5)),
                ('depot', models.ForeignKey(help_text=b'\xe5\x87\xba\xe5\x85\xa5\xe5\xba\x93\xe5\xba\x93\xe6\x88\xbf', on_delete=django.db.models.deletion.CASCADE, to='psi.Depot')),
            ],
            options={
                'verbose_name_plural': '\u51fa\u5e93\u8be6\u5355',
            },
        ),
        migrations.CreateModel(
            name='OutStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text=b'\xe5\x87\xba\xe5\xba\x93\xe5\x8d\x95\xe6\x8d\xae\xe5\x8f\xb7', max_length=30, unique=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 10, 4, 20, 19, 1, 448000), help_text=b'\xe6\x97\xa5\xe6\x9c\x9f')),
                ('hidden', models.BooleanField(default=False, help_text=b'\xe5\x88\xa0\xe9\x99\xa4\xe6\xa0\x87\xe8\xae\xb0')),
                ('returned', models.BooleanField(default=False, help_text=b'\xe9\x80\x80\xe5\xba\x93\xe6\xa0\x87\xe8\xae\xb0')),
                ('note', models.CharField(blank=True, help_text=b'\xe5\xa4\x87\xe6\xb3\xa8', max_length=100, null=True)),
                ('log', models.TextField(blank=True, help_text=b'\xe5\xa4\x87\xe6\xb3\xa8', max_length=1500, null=True)),
            ],
            options={
                'verbose_name_plural': '\u51fa\u5e93\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.DecimalField(decimal_places=2, help_text=b'\xe5\xb7\xa5\xe8\xb5\x84', max_digits=7)),
                ('date', models.DateField(default=datetime.datetime(2018, 10, 4, 20, 19, 1, 448000), help_text=b'\xe5\x8f\x91\xe8\x96\xaa\xe6\x97\xa5\xe6\x9c\x9f')),
                ('note', models.CharField(blank=True, help_text=b'\xe5\xa4\x87\xe6\xb3\xa8', max_length=100)),
            ],
            options={
                'verbose_name_plural': '\u85aa\u8d44\u53d1\u653e\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=b'\xe6\xa0\x87\xe9\xa2\x98', max_length=20)),
                ('note', models.CharField(help_text=b'\xe5\x85\xac\xe5\x91\x8a\xe5\x86\x85\xe5\xae\xb9', max_length=100)),
                ('date', models.DateField(auto_now_add=True, help_text=b'\xe5\x8f\x91\xe5\xb8\x83\xe6\x97\xa5\xe6\x9c\x9f')),
                ('hidden', models.BooleanField(default=False, help_text=b'\xe5\x88\xa0\xe9\x99\xa4\xe6\xa0\x87\xe8\xae\xb0')),
            ],
            options={
                'verbose_name_plural': '\u516c\u544a\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'\xe5\x95\x86\xe5\x93\x81\xe5\x90\x8d\xe7\xa7\xb0', max_length=30)),
                ('barcode', models.CharField(blank=True, help_text=b'\xe6\x9d\xa1\xe5\xbd\xa2\xe7\xa0\x81', max_length=20, null=True)),
                ('image', models.ImageField(blank=True, help_text=b'\xe5\x95\x86\xe5\x93\x81\xe5\x9b\xbe\xe7\x89\x87', null=True, upload_to=b'products')),
                ('size', models.CommaSeparatedIntegerField(blank=True, help_text=b"\xe5\xb0\xba\xe5\xaf\xb8,\xe8\xaf\xb7\xe4\xbd\xbf\xe7\x94\xa8','\xe5\x8f\xb7\xe5\x88\x86\xe5\x89\xb2,\xe5\xa6\x82230,180", max_length=20, null=True)),
                ('hidden', models.BooleanField(default=False, help_text=b'\xe5\x88\xa0\xe9\x99\xa4\xe6\xa0\x87\xe8\xae\xb0')),
                ('note', models.CharField(blank=True, help_text=b'\xe5\xa4\x87\xe6\xb3\xa8', max_length=100, null=True)),
                ('category', models.ForeignKey(help_text=b'\xe7\xb1\xbb\xe5\x88\xab', on_delete=django.db.models.deletion.CASCADE, to='psi.Category')),
            ],
            options={
                'verbose_name_plural': '\u5546\u54c1\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Remit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.SmallIntegerField(choices=[(1, b'\xe7\xbd\x97\xe8\x8e\xb1'), (2, b'\xe4\xbc\x98\xe5\xae\xb6'), (3, b'\xe5\xae\x9d\xe7\xbc\xa6'), (4, b'\xe5\x85\xb6\xe4\xbb\x96')], help_text=b'\xe4\xbe\x9b\xe5\xba\x94\xe5\x95\x86', max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, help_text=b'\xe9\x87\x91\xe9\xa2\x9d', max_digits=8)),
                ('date', models.DateField(default=datetime.datetime(2018, 10, 4, 20, 19, 1, 464000), help_text=b'\xe6\xb1\x87\xe6\xac\xbe\xe6\x97\xa5\xe6\x9c\x9f')),
                ('hidden', models.BooleanField(default=False, help_text=b'\xe5\x88\xa0\xe9\x99\xa4\xe6\xa0\x87\xe8\xae\xb0')),
                ('note', models.CharField(blank=True, help_text=b'\xe5\xa4\x87\xe6\xb3\xa8', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '\u6c47\u6b3e\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='SellOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text=b'\xe9\x94\x80\xe5\x94\xae\xe5\x8d\x95\xe6\x8d\xae\xe5\x8f\xb7', max_length=20, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text=b'\xe6\x8a\x98\xe6\x89\xa3\xe9\x87\x91\xe9\xa2\x9d', max_digits=8, null=True)),
                ('date', models.DateTimeField(help_text=b'\xe6\x97\xa5\xe6\x9c\x9f')),
                ('hidden', models.BooleanField(default=False, help_text=b'\xe5\x88\xa0\xe9\x99\xa4\xe6\xa0\x87\xe8\xae\xb0')),
                ('note', models.CharField(blank=True, help_text=b'\xe5\xa4\x87\xe6\xb3\xa8', max_length=100, null=True)),
                ('customer', models.ForeignKey(blank=True, help_text=b'\xe9\xa1\xbe\xe5\xae\xa2', null=True, on_delete=django.db.models.deletion.CASCADE, to='psi.Customer')),
            ],
            options={
                'verbose_name_plural': '\u9500\u552e\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='SellOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text=b'\xe6\x95\xb0\xe9\x87\x8f', max_length=4)),
                ('price', models.DecimalField(decimal_places=2, help_text=b'\xe4\xbb\xb7\xe6\xa0\xbc', max_digits=8)),
                ('oid', models.ForeignKey(help_text=b'\xe9\x94\x80\xe5\x94\xae\xe5\x8d\x95\xe6\x8d\xae\xe5\x8f\xb7', on_delete=django.db.models.deletion.CASCADE, to='psi.SellOrder')),
                ('product', models.ForeignKey(help_text=b'\xe5\x95\x86\xe5\x93\x81', on_delete=django.db.models.deletion.CASCADE, to='psi.Products')),
            ],
            options={
                'verbose_name_plural': '\u9500\u552e\u8be6\u5355',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'\xe5\xba\x97\xe9\x93\xba\xe5\x90\x8d\xe7\xa7\xb0', max_length=20)),
                ('telephone', models.CharField(help_text=b'\xe7\x94\xb5\xe8\xaf\x9d', max_length=11)),
                ('address', models.CharField(help_text=b'\xe5\x9c\xb0\xe5\x9d\x80', max_length=100)),
                ('opendate', models.DateField(default=datetime.datetime(2018, 10, 4, 20, 19, 1, 448000), help_text=b'\xe5\xbc\x80\xe4\xb8\x9a\xe6\x97\xa5\xe6\x9c\x9f')),
                ('note', models.CharField(blank=True, help_text=b'\xe5\xa4\x87\xe6\xb3\xa8', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '\u5e97\u94fa\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'\xe5\xa7\x93\xe5\x90\x8d', max_length=10)),
                ('sex', models.CharField(choices=[(b'F', b'\xe5\xa5\xb3\xe6\x80\xa7'), (b'M', b'\xe7\x94\xb7\xe6\x80\xa7')], default=b'F', help_text=b'\xe6\x80\xa7\xe5\x88\xab', max_length=2)),
                ('image', models.ImageField(blank=True, help_text=b'\xe7\x85\xa7\xe7\x89\x87', null=True, upload_to=b'staffs')),
                ('edu', models.CharField(help_text=b'\xe5\xad\xa6\xe5\x8e\x86', max_length=4)),
                ('marital', models.BooleanField(choices=[(True, b'\xe5\xb7\xb2\xe5\xa9\x9a'), (False, b'\xe6\x9c\xaa\xe5\xa9\x9a')], help_text=b'\xe5\xa9\x9a\xe5\x90\xa6')),
                ('school', models.CharField(blank=True, help_text=b'\xe6\xaf\x95\xe4\xb8\x9a\xe5\xad\xa6\xe6\xa0\xa1', max_length=100, null=True)),
                ('graduation', models.DateField(blank=True, help_text=b'\xe6\xaf\x95\xe4\xb8\x9a\xe6\x97\xa5\xe6\x9c\x9f', null=True)),
                ('address', models.CharField(help_text=b'\xe4\xbd\x8f\xe5\x9d\x80', max_length=100)),
                ('cellphone', models.CharField(help_text=b'\xe6\x89\x8b\xe6\x9c\xba', max_length=11)),
                ('idcode', models.CharField(help_text=b'\xe8\xba\xab\xe4\xbb\xbd\xe8\xaf\x81\xe5\x8f\xb7', max_length=18, unique=True)),
                ('homephone', models.CharField(help_text=b'\xe7\xb4\xa7\xe6\x80\xa5\xe8\x81\x94\xe7\xb3\xbb\xe7\x94\xb5\xe8\xaf\x9d', max_length=11)),
                ('level', models.SmallIntegerField(choices=[(1, b'\xe8\x91\xa3\xe4\xba\x8b'), (2, b'\xe4\xbc\x9a\xe8\xae\xa1'), (3, b'\xe4\xbb\x93\xe7\xae\xa1'), (4, b'\xe7\xbb\x8f\xe7\x90\x86'), (5, b'\xe5\xba\x97\xe9\x95\xbf'), (6, b'\xe5\xba\x97\xe5\x91\x98'), (7, b'\xe5\x90\x8e\xe5\x8b\xa4'), (8, b'\xe5\xae\x9e\xe4\xb9\xa0'), (9, b'\xe5\x85\xb6\xe4\xbb\x96'), (99, b'\xe7\xa6\xbb\xe8\x81\x8c')], default=6, help_text=b'\xe5\xb2\x97\xe4\xbd\x8d', max_length=2)),
                ('joindate', models.DateField(default=datetime.datetime(2018, 10, 4, 20, 19, 1, 448000), help_text=b'\xe5\x85\xa5\xe8\x81\x8c\xe6\x97\xa5\xe6\x9c\x9f')),
                ('exwork', models.CharField(blank=True, help_text=b'\xe5\xb7\xa5\xe4\xbd\x9c\xe7\xbb\x8f\xe5\x8e\x86', max_length=255, null=True)),
                ('family', models.CharField(help_text=b'\xe5\xae\xb6\xe5\xba\xad\xe6\x88\x90\xe5\x91\x98\xe5\x8f\x8a\xe5\x85\xb3\xe7\xb3\xbb', max_length=255)),
                ('note', models.CharField(blank=True, help_text=b'\xe5\xa4\x87\xe6\xb3\xa8', max_length=100, null=True)),
                ('shop', models.ForeignKey(help_text=b'\xe5\xba\x97\xe9\x93\xba', on_delete=django.db.models.deletion.CASCADE, to='psi.Shop')),
                ('user', models.ForeignKey(help_text=b'\xe7\xbb\x91\xe5\xae\x9aID', max_length=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'verbose_name_plural': '\u4eba\u5458\u7ba1\u7406',
            },
        ),
        migrations.AddField(
            model_name='sellorder',
            name='shop',
            field=models.ForeignKey(help_text=b'\xe5\xba\x97\xe9\x93\xba', on_delete=django.db.models.deletion.CASCADE, to='psi.Shop'),
        ),
        migrations.AddField(
            model_name='sellorder',
            name='staff',
            field=models.ForeignKey(help_text=b'\xe9\x94\x80\xe5\x94\xae\xe5\x91\x98\xe5\xb7\xa5', on_delete=django.db.models.deletion.CASCADE, to='psi.Staff'),
        ),
        migrations.AddField(
            model_name='remit',
            name='staff',
            field=models.ForeignKey(help_text=b'\xe6\xb1\x87\xe6\xac\xbe\xe4\xba\xba', on_delete=django.db.models.deletion.CASCADE, to='psi.Staff'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='staff',
            field=models.ForeignKey(help_text=b'\xe5\x91\x98\xe5\xb7\xa5', on_delete=django.db.models.deletion.CASCADE, to='psi.Staff'),
        ),
        migrations.AddField(
            model_name='outstream',
            name='keeper',
            field=models.ForeignKey(help_text=b'\xe4\xbb\x93\xe7\xae\xa1', on_delete=django.db.models.deletion.CASCADE, related_name='out_keeper_set', to='psi.Staff'),
        ),
        migrations.AddField(
            model_name='outstream',
            name='shop',
            field=models.ForeignKey(help_text=b'\xe6\x8f\x90\xe8\xb4\xa7\xe5\xba\x97\xe9\x93\xba', on_delete=django.db.models.deletion.CASCADE, to='psi.Shop'),
        ),
        migrations.AddField(
            model_name='outstream',
            name='staff1',
            field=models.ForeignKey(help_text=b'\xe6\x8f\x90\xe8\xb4\xa7\xe4\xba\xba\xe4\xb8\x80', on_delete=django.db.models.deletion.CASCADE, related_name='out_sells_1_set', to='psi.Staff'),
        ),
        migrations.AddField(
            model_name='outstream',
            name='staff2',
            field=models.ForeignKey(blank=True, help_text=b'\xe6\x8f\x90\xe8\xb4\xa7\xe4\xba\xba\xe4\xba\x8c', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='out_sells_2_set', to='psi.Staff'),
        ),
        migrations.AddField(
            model_name='outdetail',
            name='outid',
            field=models.ForeignKey(help_text=b'\xe5\x87\xba\xe5\xba\x93\xe5\x8d\x95ID', on_delete=django.db.models.deletion.CASCADE, to='psi.OutStream'),
        ),
        migrations.AddField(
            model_name='outdetail',
            name='product',
            field=models.ForeignKey(help_text=b'\xe5\x95\x86\xe5\x93\x81', on_delete=django.db.models.deletion.CASCADE, to='psi.Products'),
        ),
        migrations.AddField(
            model_name='instream',
            name='keeper',
            field=models.ForeignKey(help_text=b'\xe4\xbb\x93\xe7\xae\xa1', on_delete=django.db.models.deletion.CASCADE, related_name='in_keeper_set', to='psi.Staff'),
        ),
        migrations.AddField(
            model_name='instream',
            name='staff1',
            field=models.ForeignKey(help_text=b'\xe6\x94\xb6\xe8\xb4\xa7\xe4\xba\xba\xe4\xb8\x80', on_delete=django.db.models.deletion.CASCADE, related_name='in_sells_1_set', to='psi.Staff'),
        ),
        migrations.AddField(
            model_name='instream',
            name='staff2',
            field=models.ForeignKey(blank=True, help_text=b'\xe6\x94\xb6\xe8\xb4\xa7\xe4\xba\xba\xe4\xba\x8c', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_sells_2_set', to='psi.Staff'),
        ),
        migrations.AddField(
            model_name='indetail',
            name='inid',
            field=models.ForeignKey(help_text=b'\xe5\x85\xa5\xe5\xba\x93\xe5\x8d\x95ID', on_delete=django.db.models.deletion.CASCADE, to='psi.InStream'),
        ),
        migrations.AddField(
            model_name='indetail',
            name='product',
            field=models.ForeignKey(help_text=b'\xe5\x95\x86\xe5\x93\x81', on_delete=django.db.models.deletion.CASCADE, to='psi.Products'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shop',
            field=models.ForeignKey(help_text=b'\xe5\xba\x97\xe9\x93\xba', on_delete=django.db.models.deletion.CASCADE, to='psi.Shop'),
        ),
    ]
