# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 01:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('psi', '0004_auto_20181004_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='joindate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe5\x8a\xa0\xe5\x85\xa5\xe6\x97\xa5\xe6\x9c\x9f'),
        ),
        migrations.AlterField(
            model_name='instream',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 10, 5, 9, 32, 16, 939000), help_text=b'\xe6\x97\xa5\xe6\x9c\x9f'),
        ),
        migrations.AlterField(
            model_name='instream',
            name='supplier',
            field=models.SmallIntegerField(choices=[(1, b'\xe7\xbe\x85\xe8\x90\x8a'), (2, b'\xe5\x84\xaa\xe5\xae\xb6'), (3, b'\xe5\xaf\xb6\xe7\xb8\xb5'), (4, b'\xe5\x85\xb6\xe4\xbb\x96')], help_text=b'\xe4\xbe\x9b\xe5\xba\x94\xe5\x95\x86', max_length=2),
        ),
        migrations.AlterField(
            model_name='outstream',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 5, 9, 32, 16, 939000), help_text=b'\xe6\x97\xa5\xe6\x9c\x9f'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 10, 5, 9, 32, 16, 939000), help_text=b'\xe5\x8f\x91\xe8\x96\xaa\xe6\x97\xa5\xe6\x9c\x9f'),
        ),
        migrations.AlterField(
            model_name='remit',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 10, 5, 9, 32, 16, 939000), help_text=b'\xe6\xb1\x87\xe6\xac\xbe\xe6\x97\xa5\xe6\x9c\x9f'),
        ),
        migrations.AlterField(
            model_name='remit',
            name='supplier',
            field=models.SmallIntegerField(choices=[(1, b'\xe7\xbe\x85\xe8\x90\x8a'), (2, b'\xe5\x84\xaa\xe5\xae\xb6'), (3, b'\xe5\xaf\xb6\xe7\xb8\xb5'), (4, b'\xe5\x85\xb6\xe4\xbb\x96')], help_text=b'\xe4\xbe\x9b\xe5\xba\x94\xe5\x95\x86', max_length=2),
        ),
        migrations.AlterField(
            model_name='shop',
            name='opendate',
            field=models.DateField(default=datetime.datetime(2018, 10, 5, 9, 32, 16, 939000), help_text=b'\xe5\xbc\x80\xe4\xb8\x9a\xe6\x97\xa5\xe6\x9c\x9f'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='joindate',
            field=models.DateField(default=datetime.datetime(2018, 10, 5, 9, 32, 16, 939000), help_text=b'\xe5\x85\xa5\xe8\x81\x8c\xe6\x97\xa5\xe6\x9c\x9f'),
        ),
    ]
