# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 02:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('psi', '0005_auto_20181005_0932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indetail',
            options={'verbose_name_plural': '\u5165\u5eab\u8a73\u55ae'},
        ),
        migrations.AlterModelOptions(
            name='instream',
            options={'verbose_name_plural': '\u5165\u5eab\u7ba1\u7406'},
        ),
        migrations.AlterModelOptions(
            name='payslip',
            options={'verbose_name_plural': '\u85aa\u8cc7\u767c\u653e\u8a18\u9304'},
        ),
        migrations.AlterModelOptions(
            name='remit',
            options={'verbose_name_plural': '\u532f\u6b3e\u8a18\u9304'},
        ),
        migrations.AlterModelOptions(
            name='sellorderdetail',
            options={'verbose_name_plural': '\u92b7\u552e\u8a73\u55ae'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name_plural': '\u5e97\u8216\u7ba1\u7406'},
        ),
        migrations.AlterField(
            model_name='indetail',
            name='depot',
            field=models.ForeignKey(help_text=b'\xe5\x87\xba\xe5\x85\xa5\xe5\xba\xab\xe5\xba\xab\xe6\x88\xbf', on_delete=django.db.models.deletion.CASCADE, to='psi.Depot'),
        ),
        migrations.AlterField(
            model_name='indetail',
            name='depotdetail',
            field=models.CharField(blank=True, help_text=b'\xe5\x87\xba\xe5\x85\xa5\xe5\xba\xab\xe8\xa9\xb3\xe7\xb4\xb0\xe4\xbd\x8d\xe7\xbd\xae', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='indetail',
            name='inid',
            field=models.ForeignKey(help_text=b'\xe5\x85\xa5\xe5\xba\xab\xe5\x96\xaeID', on_delete=django.db.models.deletion.CASCADE, to='psi.InStream'),
        ),
        migrations.AlterField(
            model_name='indetail',
            name='quantity',
            field=models.IntegerField(help_text=b'\xe6\x95\xb8\xe9\x87\x8f'),
        ),
        migrations.AlterField(
            model_name='indetail',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text=b'\xe5\xbb\xa0\xe6\x96\xb9\xe9\x80\xb2\xe5\x83\xb9', max_digits=8),
        ),
        migrations.AlterField(
            model_name='instream',
            name='code',
            field=models.CharField(help_text=b'\xe5\x85\xa5\xe5\xba\xab\xe5\x96\xae\xe8\x99\x9f', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='instream',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe6\x97\xa5\xe6\x9c\x9f'),
        ),
        migrations.AlterField(
            model_name='instream',
            name='hidden',
            field=models.BooleanField(default=False, help_text=b'\xe5\x88\xaa\xe9\x99\xa4\xe6\xa8\x99\xe8\xa8\x98'),
        ),
        migrations.AlterField(
            model_name='instream',
            name='keeper',
            field=models.ForeignKey(help_text=b'\xe5\x80\x89\xe7\xae\xa1', on_delete=django.db.models.deletion.CASCADE, related_name='in_keeper_set', to='psi.Staff'),
        ),
        migrations.AlterField(
            model_name='instream',
            name='log',
            field=models.TextField(blank=True, help_text=b'\xe5\x82\x99\xe8\xa8\xbb', max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='instream',
            name='note',
            field=models.CharField(blank=True, help_text=b'\xe5\x82\x99\xe8\xa8\xbb', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instream',
            name='staff1',
            field=models.ForeignKey(help_text=b'\xe6\x94\xb6\xe8\xb2\xa8\xe4\xba\xba\xe4\xb8\x80', on_delete=django.db.models.deletion.CASCADE, related_name='in_sells_1_set', to='psi.Staff'),
        ),
        migrations.AlterField(
            model_name='instream',
            name='staff2',
            field=models.ForeignKey(blank=True, help_text=b'\xe6\x94\xb6\xe8\xb2\xa8\xe4\xba\xba\xe4\xba\x8c', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_sells_2_set', to='psi.Staff'),
        ),
        migrations.AlterField(
            model_name='instream',
            name='supplier',
            field=models.SmallIntegerField(choices=[(1, b'\xe7\xbe\x85\xe8\x90\x8a'), (2, b'\xe5\x84\xaa\xe5\xae\xb6'), (3, b'\xe5\xaf\xb6\xe7\xb8\xb5'), (4, b'\xe5\x85\xb6\xe4\xbb\x96')], help_text=b'\xe4\xbe\x9b\xe6\x87\x89\xe5\x95\x86'),
        ),
        migrations.AlterField(
            model_name='outdetail',
            name='quantity',
            field=models.IntegerField(help_text=b'\xe6\x95\xb0\xe9\x87\x8f'),
        ),
        migrations.AlterField(
            model_name='outstream',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 5, 10, 8, 50, 126000), help_text=b'\xe6\x97\xa5\xe6\x9c\x9f'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe7\x99\xbc\xe8\x96\xaa\xe6\x97\xa5\xe6\x9c\x9f'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='note',
            field=models.CharField(blank=True, help_text=b'\xe5\x82\x99\xe8\xa8\xbb', max_length=100),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='pay',
            field=models.DecimalField(decimal_places=2, help_text=b'\xe5\xb7\xa5\xe8\xb3\x87', max_digits=7),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='staff',
            field=models.ForeignKey(help_text=b'\xe5\x93\xa1\xe5\xb7\xa5', on_delete=django.db.models.deletion.CASCADE, to='psi.Staff'),
        ),
        migrations.AlterField(
            model_name='products',
            name='barcode',
            field=models.CharField(blank=True, help_text=b'\xe6\xa2\x9d\xe5\xbd\xa2\xe7\xa2\xbc', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(help_text=b'\xe9\xa1\x9e\xe5\x88\xa5', on_delete=django.db.models.deletion.CASCADE, to='psi.Category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='hidden',
            field=models.BooleanField(default=False, help_text=b'\xe5\x88\xaa\xe9\x99\xa4\xe6\xa8\x99\xe8\xa8\x98'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, help_text=b'\xe5\x95\x86\xe5\x93\x81\xe5\x9c\x96\xe7\x89\x87', null=True, upload_to=b'products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(help_text=b'\xe5\x95\x86\xe5\x93\x81\xe5\x90\x8d\xe7\xa8\xb1', max_length=30),
        ),
        migrations.AlterField(
            model_name='products',
            name='note',
            field=models.CharField(blank=True, help_text=b'\xe5\x82\x99\xe8\xa8\xbb', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, help_text=b"\xe5\xb0\xba\xe5\xaf\xb8,\xe8\xab\x8b\xe4\xbd\xbf\xe7\x94\xa8','\xe8\x99\x9f\xe5\x88\x86\xe5\x89\xb2,\xe5\xa6\x82230,180", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='remit',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 10, 5, 10, 8, 50, 129000), help_text=b'\xe5\xbc\x80\xe4\xb8\x9a\xe6\x97\xa5\xe6\x9c\x9f'),
        ),
        migrations.AlterField(
            model_name='remit',
            name='hidden',
            field=models.BooleanField(default=False, help_text=b'\xe5\x88\xaa\xe9\x99\xa4\xe6\xa8\x99\xe8\xa8\x98'),
        ),
        migrations.AlterField(
            model_name='remit',
            name='note',
            field=models.CharField(blank=True, help_text=b'\xe5\x82\x99\xe8\xa8\xbb', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='remit',
            name='staff',
            field=models.ForeignKey(help_text=b'\xe5\x8c\xaf\xe6\xac\xbe\xe4\xba\xba', on_delete=django.db.models.deletion.CASCADE, to='psi.Staff'),
        ),
        migrations.AlterField(
            model_name='remit',
            name='supplier',
            field=models.SmallIntegerField(choices=[(1, b'\xe7\xbe\x85\xe8\x90\x8a'), (2, b'\xe5\x84\xaa\xe5\xae\xb6'), (3, b'\xe5\xaf\xb6\xe7\xb8\xb5'), (4, b'\xe5\x85\xb6\xe4\xbb\x96')], help_text=b'\xe4\xbe\x9b\xe6\x87\x89\xe5\x95\x86'),
        ),
        migrations.AlterField(
            model_name='sellorderdetail',
            name='oid',
            field=models.ForeignKey(help_text=b'\xe9\x8a\xb7\xe5\x94\xae\xe5\x96\xae\xe6\x93\x9a\xe8\x99\x9f', on_delete=django.db.models.deletion.CASCADE, to='psi.SellOrder'),
        ),
        migrations.AlterField(
            model_name='sellorderdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text=b'\xe5\x83\xb9\xe6\xa0\xbc', max_digits=8),
        ),
        migrations.AlterField(
            model_name='sellorderdetail',
            name='quantity',
            field=models.IntegerField(help_text=b'\xe6\x95\xb8\xe9\x87\x8f'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(help_text=b'\xe5\xba\x97\xe9\x8b\xaa\xe5\x90\x8d\xe7\xa8\xb1', max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='note',
            field=models.CharField(blank=True, help_text=b'\xe5\x82\x99\xe8\xa8\xbb', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='opendate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe9\x96\x8b\xe6\xa5\xad\xe6\x97\xa5\xe6\x9c\x9f'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='telephone',
            field=models.CharField(help_text=b'\xe9\x9b\xbb\xe8\xa9\xb1', max_length=11),
        ),
        migrations.AlterField(
            model_name='staff',
            name='joindate',
            field=models.DateField(default=datetime.date(2018, 10, 5), help_text=b'\xe5\x85\xa5\xe8\x81\x8c\xe6\x97\xa5\xe6\x9c\x9f'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='level',
            field=models.SmallIntegerField(choices=[(1, b'\xe8\x91\xa3\xe4\xba\x8b'), (2, b'\xe4\xbc\x9a\xe8\xae\xa1'), (3, b'\xe4\xbb\x93\xe7\xae\xa1'), (4, b'\xe7\xbb\x8f\xe7\x90\x86'), (5, b'\xe5\xba\x97\xe9\x95\xbf'), (6, b'\xe5\xba\x97\xe5\x91\x98'), (7, b'\xe5\x90\x8e\xe5\x8b\xa4'), (8, b'\xe5\xae\x9e\xe4\xb9\xa0'), (9, b'\xe5\x85\xb6\xe4\xbb\x96'), (99, b'\xe7\xa6\xbb\xe8\x81\x8c')], default=6, help_text=b'\xe5\xb2\x97\xe4\xbd\x8d'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.ForeignKey(help_text=b'\xe7\xbb\x91\xe5\xae\x9aID', max_length=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
