# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 03:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('psi', '0006_auto_20181005_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outstream',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text=b'\xe6\x97\xa5\xe6\x9c\x9f'),
        ),
        migrations.AlterField(
            model_name='remit',
            name='date',
            field=models.DateField(default=datetime.date(2018, 10, 5), help_text=b'\xe5\x8c\xaf\xe6\xac\xbe\xe6\x97\xa5\xe6\x9c\x9f'),
        ),
    ]
