# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('psi', '0007_auto_20181005_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remit',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe5\x8c\xaf\xe6\xac\xbe\xe6\x97\xa5\xe6\x9c\x9f'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='joindate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe5\x88\xb0\xe8\x81\xb7\xe6\x97\xa5\xe6\x9c\x9f'),
        ),
    ]
