# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-06 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psi', '0008_auto_20181005_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': '\u4eba\u54e1\u7ba1\u7406'},
        ),
        migrations.AlterField(
            model_name='staff',
            name='cellphone',
            field=models.CharField(help_text=b'\xe6\x89\x8b\xe6\xa9\x9f', max_length=11),
        ),
        migrations.AlterField(
            model_name='staff',
            name='edu',
            field=models.CharField(help_text=b'\xe5\xad\xb8\xe6\xad\xb7', max_length=4),
        ),
        migrations.AlterField(
            model_name='staff',
            name='exwork',
            field=models.CharField(blank=True, help_text=b'\xe5\xb7\xa5\xe4\xbd\x9c\xe7\xb6\x93\xe6\xad\xb7', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='family',
            field=models.CharField(help_text=b'\xe5\xae\xb6\xe5\xba\xad\xe6\x88\x90\xe5\x93\xa1\xe5\x8f\x8a\xe9\x97\x9c\xe4\xbf\x82', max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='graduation',
            field=models.DateField(blank=True, help_text=b'\xe7\x95\xa2\xe6\xa5\xad\xe6\x97\xa5\xe6\x9c\x9f', null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='homephone',
            field=models.CharField(help_text=b'\xe7\xb7\x8a\xe6\x80\xa5\xe8\x81\xaf\xe7\xb9\xab\xe9\x9b\xbb\xe8\xa9\xb1', max_length=11),
        ),
        migrations.AlterField(
            model_name='staff',
            name='idcode',
            field=models.CharField(help_text=b'\xe8\xba\xab\xe4\xbb\xbd\xe8\xad\x89\xe8\x99\x9f', max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='level',
            field=models.SmallIntegerField(choices=[(1, b'\xe8\x91\xa3\xe4\xba\x8b'), (2, b'\xe6\x9c\x83\xe8\xa8\x88'), (3, b'\xe5\x80\x89\xe7\xae\xa1'), (4, b'\xe7\xb6\x93\xe7\x90\x86'), (5, b'\xe5\xba\x97\xe9\x95\xb7'), (6, b'\xe5\xba\x97\xe5\x93\xa1'), (7, b'\xe5\xbe\x8c\xe5\x8b\xa4'), (8, b'\xe5\xaf\xa6\xe7\xbf\x92'), (9, b'\xe5\x85\xb6\xe4\xbb\x96'), (99, b'\xe9\x9b\xa2\xe8\x81\xb7')], default=6, help_text=b'\xe8\x81\xb7\xe4\xbd\x8d'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='note',
            field=models.CharField(blank=True, help_text=b'\xe5\x82\x99\xe8\xa8\xbb', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='school',
            field=models.CharField(blank=True, help_text=b'\xe7\x95\xa2\xe6\xa5\xad\xe5\xad\xb8\xe6\xa0\xa1', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='shop',
            field=models.ForeignKey(help_text=b'\xe5\xba\x97\xe9\x8b\xaa', on_delete=django.db.models.deletion.CASCADE, to='psi.Shop'),
        ),
    ]
