# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-06 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psi', '0009_auto_20181006_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='level',
            field=models.SmallIntegerField(default=6, help_text=b'\xe8\x81\xb7\xe4\xbd\x8d'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='marital',
            field=models.BooleanField(default=True, help_text=b'\xe5\xa9\x9a\xe5\x90\xa6'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sex',
            field=models.CharField(default=b'M', help_text=b'\xe6\x80\xa7\xe5\x88\xab', max_length=2),
        ),
    ]
