# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-27 06:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psi', '0010_auto_20181006_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '\u5206\u985e\u7ba1\u7406'},
        ),
        migrations.RemoveField(
            model_name='staff',
            name='shop',
        ),
        migrations.AlterField(
            model_name='category',
            name='hidden',
            field=models.BooleanField(default=False, help_text=b'\xe6\x98\xaf\xe5\x90\xa6\xe9\x9a\xb1\xe8\x97\x8f'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text=b'\xe5\x88\x86\xe9\xa1\x9e\xe5\x90\x8d\xe7\xa8\xb1', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='pid',
            field=models.ForeignKey(blank=True, help_text=b'\xe7\x88\xb6\xe7\xb4\x9a\xe5\x88\x86\xe9\xa1\x9e', null=True, on_delete=django.db.models.deletion.CASCADE, to='psi.Category'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='level',
            field=models.SmallIntegerField(choices=[(1, b'\xe8\x91\xa3\xe4\xba\x8b'), (2, b'\xe6\x9c\x83\xe8\xa8\x88'), (3, b'\xe5\x80\x89\xe7\xae\xa1'), (4, b'\xe7\xb6\x93\xe7\x90\x86'), (5, b'\xe5\xba\x97\xe9\x95\xb7'), (6, b'\xe5\xba\x97\xe5\x93\xa1'), (7, b'\xe5\xbe\x8c\xe5\x8b\xa4'), (8, b'\xe5\xaf\xa6\xe7\xbf\x92'), (9, b'\xe5\x85\xb6\xe4\xbb\x96'), (99, b'\xe9\x9b\xa2\xe8\x81\xb7')], default=6, help_text=b'\xe8\x81\xb7\xe4\xbd\x8d'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
