# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-27 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psi', '0011_auto_20181027_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='shop',
            field=models.ManyToManyField(to='psi.Shop'),
        ),
    ]
