# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-27 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psi', '0012_staff_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='sex',
            field=models.CharField(choices=[(b'F', b'\xe5\xa5\xb3\xe6\x80\xa7'), (b'M', b'\xe7\x94\xb7\xe6\x80\xa7')], default=b'F', help_text=b'\xe6\x80\xa7\xe5\x88\xab', max_length=2),
        ),
    ]
